# Generated by Django 5.0.6 on 2024-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='bitcoin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='etheriun',
            field=models.FloatField(),
        ),
    ]
