# Generated by Django 5.0.6 on 2024-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
