# Generated by Django 5.0.6 on 2024-06-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='bond',
            new_name='live_update',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='price_per_bond',
        ),
    ]
