# Generated by Django 5.0.6 on 2024-06-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_bond_stock_live_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='live_update',
            new_name='live_percent',
        ),
    ]
