# Generated by Django 5.0.6 on 2024-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_live_update_stock_live_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_profit',
        ),
        migrations.AddField(
            model_name='buystock',
            name='is_profit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buystock',
            name='percent_live',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='live_percent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
