# Generated by Django 5.0.6 on 2024-06-15 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stock_is_profit_buystock_is_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buystock',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='buystock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buystock',
            name='percent_live',
            field=models.FloatField(default=0.4),
        ),
    ]
