# Generated by Django 5.0.6 on 2024-06-21 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_buystock_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
