# Generated by Django 5.0.6 on 2024-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='sold_for',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
