# Generated by Django 5.0.6 on 2024-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_exchangetrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='crypto_type',
            field=models.CharField(default='bitcoin', max_length=100),
            preserve_default=False,
        ),
    ]
