# Generated by Django 5.0.6 on 2024-07-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_exchangetrade_crypto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='r_wallet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
